From cfd33730868350cd475e45569a8c1573803a6895 Mon Sep 17 00:00:00 2001
From: dineshbhor <dinesh.bhor@nttdata.com>
Date: Fri, 17 Mar 2017 16:34:20 +0530
Subject: [PATCH] Fix failing PY2 and PY3 gate jobs

Please refer:
http://logs.openstack.org/43/446943/1/check/gate-python-keystoneclient-python27-ubuntu-xenial/84b965d/console.html

Closes-Bug: #1673761
Change-Id: Iefa74ffe8642f039a115e9ff4416c8f72d299317
---
 keystoneclient/tests/unit/apiclient/test_exceptions.py | 2 +-
 keystoneclient/tests/unit/test_http.py                 | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/keystoneclient/tests/unit/apiclient/test_exceptions.py b/keystoneclient/tests/unit/apiclient/test_exceptions.py
index 4a803c7..ddf8d98 100644
--- a/keystoneclient/tests/unit/apiclient/test_exceptions.py
+++ b/keystoneclient/tests/unit/apiclient/test_exceptions.py
@@ -40,7 +40,7 @@ class ExceptionsArgsTest(utils.TestCase):
             method,
             url)
         self.assertIsInstance(ex, ex_cls)
-        self.assertEqual(ex.message, json_data["error"]["message"])
+        self.assertIn(json_data["error"]["message"], ex.message)
         self.assertEqual(ex.details, json_data["error"]["details"])
         self.assertEqual(ex.method, method)
         self.assertEqual(ex.url, url)
diff --git a/keystoneclient/tests/unit/test_http.py b/keystoneclient/tests/unit/test_http.py
index 6e0070a..0282f1a 100644
--- a/keystoneclient/tests/unit/test_http.py
+++ b/keystoneclient/tests/unit/test_http.py
@@ -97,7 +97,7 @@ class ClientTest(utils.TestCase):
                 cl.get('/hi')
         except exceptions.BadRequest as exc:
             exc_raised = True
-            self.assertEqual(exc.message, "Error message string")
+            self.assertEqual(exc.message, "Error message string (HTTP 400)")
         self.assertTrue(exc_raised, 'Exception not raised.')
 
     def test_post(self):
-- 
2.12.2

